blazemeter.blazemeter_user.*:
  type: config_entity
  label: 'Blazemeter user config'
  mapping:
    id:
      type: string
      label: 'ID'
    username:
      type: string
      label: 'Username'
    password:
      type: string
      label: 'Password'